services:
  - type: web
    name: lab1as-backend
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/lab1As-0.0.1-SNAPSHOT.jar
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: PORT
        value: 10000
